### PR TITLE
WIP: Alpine based image

### PR DESCRIPTION
**Pull request by dx9**
Nice gains here. Virtual SIze 540MB to 60MB. Compressed 168MB to 18MB.

Working through the side effects...

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Just a heads up, the swarm binary is not needed and can be dropped.

**Comment by ibuildthecloud** [comment]
dnsmasq also not needed

**Comment by ibuildthecloud** [comment]
I think we need real GNU sed, grep, and head.  Does alpine have gnu coreutils?

**Comment by ibuildthecloud** [comment]
Don't know what version of haproxy you have, but 1.5+ is required

**Comment by dx9** [comment]
Thanks for the heads up. Dropped dnsmasq and swarm. Alpine packs haproxy 1.5 and coreutils. Got it booting after finding all the tweaks. Image is at 43MB Virt / 16 MB Comp

More testing to do still, but this baby is rockin in Alpine! ;) I'll update the PRs and get a branch in rancher out to run the stack so it is easy to poke.

**Comment by mishak87** [comment]
I noticed there has not been a progress for a while can I help?

**Comment by cjellick** [comment]
Very stale. Closing

**Pull request closed without merging**
